-DTAU_PURE_FORTRAN_INSTRUMENTATION is no longer needed.  The instrumentor puts in the pure instrumentation regardless, so we may as well define these. Otherwise you will get:
pure.o(.text+0x112): In function `calculate_':
: undefined reference to `tau_pure_start_'
pure.o(.text+0x138): In function `calculate_':
: undefined reference to `tau_pure_stop_'
pure.o(.text+0x15d): In function `foo_':
: undefined reference to `tau_pure_start_'
pure.o(.text+0x17c): In function `foo_':
: undefined reference to `tau_pure_stop_'


git-svn-id: file:///mnt/fast/tau2git/svnroot/trunk/tau2@4374 a8e31b63-e6ca-409b-a01b-2eec1b506579