Added -print-prog-name=ld and -print-search-dirs to the list of options where we just go straight to the compiler.
---------- Forwarded message ----------
Date: Mon, 08 Jan 2007 11:39:34 -0700
From: Sid Sydoriak <sxs@lanl.gov>
To: Sameer Shende <sameer@cs.uoregon.edu>
Subject: tau_cxx.sh alteration

Sameer,

Whenever I remake tau_cxx.sh, I have to remember to put in two
modifications which are necessary for using tau_cxx.sh in our build
system. In order to create the Makefiles, we use a locally written
script build.pl to run automake and all that stuff. There are two checks
written into build.pl that make the following two calls to g++ and
analyze the output from those commands:

cy-c1.lanl.gov:/scratch2/sxs/packages/tau-2.16/x86_64/bin% g++
-print-search-dirs
install: /usr/lib/gcc/x86_64-redhat-linux/3.4.4/
programs:
=/usr/libexec/gcc/x86_64-redhat-linux/3.4.4/:/usr/libexec/gcc/x86_64-redhat-linux/3.4.4/:/usr
/libexec/gcc/x86_64-redhat-linux/:/usr/lib/gcc/x86_64-redhat-linux/3.4.4/:/usr/lib/gcc/x86_64
-redhat-linux/:/usr/libexec/gcc/x86_64-redhat-linux/3.4.4/:/usr/libexec/gcc/x86_64-redhat-lin
ux/:/usr/lib/gcc/x86_64-redhat-linux/3.4.4/:/usr/lib/gcc/x86_64-redhat-linux/:/usr/lib/gcc/x8
6_64-redhat-linux/3.4.4/../../../../x86_64-redhat-linux/bin/x86_64-redhat-linux/3.4.4/:/usr/l
ib/gcc/x86_64-redhat-linux/3.4.4/../../../../x86_64-redhat-linux/bin/
libraries:
=/usr/lib/gcc/x86_64-redhat-linux/3.4.4/:/usr/lib/gcc/x86_64-redhat-linux/3.4.4/:/usr/lib/gcc
/x86_64-redhat-linux/3.4.4/../../../../x86_64-redhat-linux/lib/x86_64-redhat-linux/3.4.4/:/us
r/lib/gcc/x86_64-redhat-linux/3.4.4/../../../../x86_64-redhat-linux/lib/:/usr/lib/gcc/x86_64-
redhat-linux/3.4.4/../../../x86_64-redhat-linux/3.4.4/:/usr/lib/gcc/x86_64-redhat-linux/3.4.4
/../../../:/lib/x86_64-redhat-linux/3.4.4/:/lib/:/usr/lib/x86_64-redhat-linux/3.4.4/:/usr/lib
/
cy-c1.lanl.gov:/scratch2/sxs/packages/tau-2.16/x86_64/bin% g++
-print-prog-name=ld
ld
cy-c1.lanl.gov:/scratch2/sxs/packages/tau-2.16/x86_64/bin%

When creating the Makefiles that use CXX = tau_cxx.sh, however,
tau_cxx.sh's verbose nature causes the output to look erroneous to
build.pl, and build.pl exits.


cy-c1.lanl.gov:/scratch2/sxs/packages/tau-2.16/x86_64/bin%
tau_cxx.sh-orig -print-prog-name=ld


Debug: Linking with TAU Options
Executing> g++ -print-prog-name=ld
-L/scratch2/sxs/packages/tau-2.16/x86_64/lib -lTauMpi-gnu-mpi-pdt
-L/opt/OpenMPI/openmpi-1.1.2/ib/lib64 -lmpi -lmpi_cxx
-L/scratch2/sxs/packages/tau-2.16/x86_64/lib -ltau-gnu-mpi-pdt
-L/usr/lib/gcc/x86_64-redhat-linux/3.4.4/ -lstdc++ -lgcc_s -o a.out
ld
Error: Tried Looking for file: a.out
Error: Command(Executable) is -- g++
Error: Full Command attempted is -- g++ -print-prog-name=ld
-L/scratch2/sxs/packages/tau-2.16/x86_64/lib -lTauMpi-gnu-mpi-pdt
-L/opt/OpenMPI/openmpi-1.1.2/ib/lib64 -lmpi -lmpi_cxx
-L/scratch2/sxs/packages/tau-2.16/x86_64/lib
-ltau-gnu-mpi-pdt
-L/usr/lib/gcc/x86_64-redhat-linux/3.4.4/   -lstdc++ -lgcc_s    -o a.out
Error: Reverting to a Regular Make

Reverting to uninstrumented command disabled. To enable reverting pass
-optRevert to tau_compiler.sh.
make: *** [all] Error 1
cy-c1.lanl.gov:/scratch2/sxs/packages/tau-2.16/x86_64/bin%

So I have hacked in a fix that is not as general as it should be.  You
might want to think about about a more general way of making tau_cxx.sh
compatible with g++ in these situations.  I can think of clunky ways of
doing this.  Like an expandable list of options (within the tau_cxx.sh
code) that will not produce verbose output.  Or an environment variable
that has a list of silent options, which will be read from a file in
tau_cxx.sh's directory that will not be destroyed when making
tau_cxx.sh. ... ?

Any way here's my hacked fix:

for arg in "$@"
do
  case $arg in
    -print-prog-name=ld)
      g++ $arg
      exit 0
      shift
      ;;
    -print-search-dirs)
      g++ $arg
      exit 0
      ;;
    -tau_makefile=*)
      MAKEFILE=`echo $arg | sed -e 's/-tau_makefile=//'`
      .....


   -Sid


git-svn-id: file:///mnt/fast/tau2git/svnroot/trunk/tau2@4601 a8e31b63-e6ca-409b-a01b-2eec1b506579