The CFLAGS was missing a $(DEFINES) which contains -DLIBRARY_SOURCE. Without this define, we couldn't compile TauWrapSyscalls.c to a .o. It gets:
gcc     -g -O2 -I/home/users/sameer/tau2/include -I/home/users/sameer/tau2/include/Profile -DPROFILING_ON                        -DTAU_GNU -DTAU_DOT_H_LESS_HEADERS                      -DTAU_LINUX_TIMERS                                 -DTAU_LARGEFILE -D_LARGEFILE64_SOURCE                    -DTAU_BFD        -fPIC     -c TauWrapSyscalls.c
TauWrapSyscalls.c:110:16: macro "fork" passed 1 arguments, but takes just 0
TauWrapSyscalls.c:110: error: syntax error before '{' token
TauWrapSyscalls.c:116: error: syntax error before "if"
TauWrapSyscalls.c:120: error: syntax error before string constant
TauWrapSyscalls.c:120: warning: data definition has no type or storage class
TauWrapSyscalls.c:121: error: initializer element is not constant
TauWrapSyscalls.c:121: warning: data definition has no type or storage class
TauWrapSyscalls.c:123: error: syntax error before "if"
...
without the $(DEFINES). Does anyone remember why $(DEFINES) was not included in $(CFLAGS) but included in $(CXXFLAGS)? I think it should be included.