Removed SSL code, it was causing the following error when used with the IBM JRE:
Exception in thread "main" java.lang.NoClassDefFoundError: com/sun/net/ssl/internal/ssl/Provider


git-svn-id: file:///mnt/fast/tau2git/svnroot/trunk/tau2@4727 a8e31b63-e6ca-409b-a01b-2eec1b506579