Changed: using namespace std; #include <iostream>
to

#include <iostream>
using namespace std;

this caused problems with the older Intel compilers [Avi, TACC].

cd vtfconverter; make "MAKE=make" "CFLAGS= -I../include
-DTAU_DOT_H_LESS_HEADERS -DTAU_INTEL  -w    "
make[2]: Entering directory `/opt/apps/tau/tau-2.14.2/utils/vtfconverter'
icpc   -I../include -DTAU_DOT_H_LESS_HEADERS -DTAU_INTEL  -w
-I/opt/apps/tau/vtf3-1.33/include -c node.cc
icpc   -I../include -DTAU_DOT_H_LESS_HEADERS -DTAU_INTEL  -w
-I/opt/apps/tau/vtf3-1.33/include -c tray.cc
tray.h(35): error: name must be a namespace name
  using namespace std;
                  ^

compilation aborted for tray.cc (code 2)
make[2]: *** [tray.o] Error 2
make[2]: Leaving directory `/opt/apps/tau/tau-2.14.2/utils/vtfconverter'


git-svn-id: file:///mnt/fast/tau2git/svnroot/trunk/tau2@3160 a8e31b63-e6ca-409b-a01b-2eec1b506579