ROCm 6.2.0 introduced a lock to avoid multiple instances of rocprofiler (ROCm 6.2.4 has this lock). https://github.com/ROCm/rocprofiler/commits/a5192bb9b337a930b0179653ec8785336f92859e/src/core/profiling_lock.cpp
This change has introduced a racing condition where sometimes profiling applications with MPI and rocprofiler thows:

ERROR: rocprofiler_pool_open(),
A profiling instance already exists! Multiple profiling instances are not allowed.

This lock can be avoided using ONLY roctracer. Disabled rocprofiler by default when building for ROCm, rocprofiler or roctracer must be selected.

Tested for both ROCm 5.* and ROCm 6.*
Configuration example ROCm 5.*: -c++=hipcc -cc=amdclang -fortran=mpif90 -bfd=download -rocm=/opt/rocm-5.5.0 -roctracer=/opt/rocm-5.5.0/roctracer/ -mpi
Configuration example for ROCm 6.*: -c++=mpicxx -cc=mpicc -fortran=mpif90 -rocm=/opt/rocm-6.2.3 -roctracer=/opt/rocm-6.2.3 -mpi -bfd=download


Former-commit-id: 5df258e975df60480a4dfdfd64c121d505ff759f