We need to test the memory allocation statements more extensively. This fixes bug #0000221 in getVariableName:
[sameer@zorak f90]$ cat f.f90
      program foo

      type pw_type
        integer :: in_use
      end type pw_type

      type mystruct
        integer:: n
        TYPE(pw_type), POINTER :: pw
      end type mystruct

      TYPE(mystruct), DIMENSION(:), POINTER :: tmp_a, tmp_b

      integer stat, ispin

      ispin = 4
      NULLIFY(tmp_a, tmp_b)

      ALLOCATE(tmp_a(ispin), tmp_b(ispin))

      ALLOCATE(tmp_a(ispin)%pw, tmp_b(ispin)%pw)

      end program foo
[sameer@zorak f90]$ tau_f90.sh f.f90


Debug: Parsing with PDT Parser
Executing> /usr/local/packages/pdtoolkit-3.11/x86_64/bin/f95parse f.f90
-I/home/users/sameer/tau2/include


Debug: Instrumenting with TAU
Executing> /home/users/sameer/tau2/x86_64/bin/tau_instrumentor f.pdb f.f90
-o f.inst.f90 -f select.tau


Debug: Compiling (Individually) with Instrumented Code
Executing> ifort -I. -c f.inst.f90 -I/home/users/sameer/tau2/include -o
f.o
fortcom: Error: f.inst.f90, line 35: This intrinsic procedure reference
contains too many arguments.   [SIZEOF]
       call TAU_ALLOC(tmp_a(ispin)%pw, tmp_b(ispin)%pw, 21,
sizeof(tmp_a(ispin)%pw, tmp_b(ispin)%pw), '&
------------------------------------------------------------^
compilation aborted for f.inst.f90 (code 1)
Error: Tried Looking for file: f.o
Error: Command(Executable) is -- ifort
Error: Full Command attempted is -- ifort   -I. -c  f.inst.f90
-I/home/users/sameer/tau2/include  -o f.o
Error: Reverting to a Regular Make



Debug: Linking (Together) object files
Executing> ifort f.o -L/home/users/sameer/tau2/x86_64/lib -ltau-icpc-pdt
-L/usr/lib/gcc/x86_64-redhat-linux/3.4.6/ -L/usr/bin/../lib64 -lstdc++
-lgcc_s -lcxa -lunwind -o a.out
IPO Warning: can not find "f.o"
ld: f.o: No such file: No such file or directory
Error: Tried Looking for file: a.out
Error: Command(Executable) is -- ifort
Error: Full Command attempted is -- ifort   f.o
-L/home/users/sameer/tau2/x86_64/lib -ltau-icpc-pdt
-L/usr/lib/gcc/x86_64-redhat-linux/3.4.6/ -L/usr/bin/../lib64 -lstdc++
-lgcc_s  -lcxa -lunwind   -o a.out
Error: Reverting to a Regular Make



Debug: Compiling with Non-Instrumented Regular Code
Executing> ifort f.f90

[sameer@zorak f90]$ cat f.inst.f90
      program foo

      type pw_type
        integer :: in_use
      end type pw_type

      type mystruct
        integer:: n
        TYPE(pw_type), POINTER :: pw
      end type mystruct

      TYPE(mystruct), DIMENSION(:), POINTER :: tmp_a, tmp_b

      integer stat, ispin


      integer profiler(2) / 0, 0 /
      save profiler

      call TAU_PROFILE_INIT()
      call TAU_PROFILE_TIMER(profiler, 'FOO [{f.f90} {1,15}]')
      call TAU_PROFILE_START(profiler)
      ispin = 4
      NULLIFY(tmp_a, tmp_b)


      ALLOCATE(tmp_a(ispin), tmp_b(ispin))

       call TAU_ALLOC(tmp_a, 19, sizeof(tmp_a), 'f.f90, variable=tmp_a')
       call TAU_ALLOC(tmp_b, 19, sizeof(tmp_b), 'f.f90, variable=tmp_b')


      ALLOCATE(tmp_a(ispin)%pw, tmp_b(ispin)%pw)

       call TAU_ALLOC(tmp_a(ispin)%pw, tmp_b(ispin)%pw, 21,
sizeof(tmp_a(ispin)%pw, tmp_b(ispin)%pw), '&
     &f.f90, variable=tmp_a(ispin)%pw, tmp_b(ispin)%pw')

      call TAU_PROFILE_STOP(profiler)
      end program foo


git-svn-id: file:///mnt/fast/tau2git/svnroot/trunk/tau2@5476 a8e31b63-e6ca-409b-a01b-2eec1b506579