Static member functions in a class template were being instrumented with CT(*this). We need to see the prototype instantiation and see if the routine pointed to by this item is static. This was pointed out by Dan Katz, Profitlogic: The next problem on the hit parade seems to be with the instrumentation of static member functions in template classes.  In particular, I have a template class (full code attached, as usual):
------------------------------------------------------------------------
template<typename bar>
class foo
{
public:
    static void
    goodbye()
    {
        cout << "Goodbye, World" << endl;
    }
private:
    bar mBar;
};
------------------------------------------------------------------------

which gets instrumented to

------------------------------------------------------------------------
template<typename bar>
class foo
{
public:
    static void
    goodbye()
    {
  TAU_PROFILE("foo<bar>::goodbye", CT(*this), TAU_USER);

        cout << "Goodbye, World" << endl;
    }
private:
    bar mBar;
};
------------------------------------------------------------------------

at which point the compiler correctly complains that static members
don't have a 'this' to point to:

------------------------------------------------------------------------
hello.inst.cpp: In static member function `static void foo<bar>::goodbye()':
hello.inst.cpp:14: error: `this' is unavailable for static member functions
------------------------------------------------------------------------


I did a quick check and didn't have this problem with a static member
in a normal class, only in a template class.
From: Dan Katz <dkatz@profitlogic.com>

This is now fixed.


git-svn-id: file:///mnt/fast/tau2git/svnroot/trunk/tau2@2275 a8e31b63-e6ca-409b-a01b-2eec1b506579